### ISSUE TITLE
[BUG] in Get service type with invalid id (string/special Character/numeric)

### ISSUE THREAD

**Issue by Luqmanhanung** [ProjectBengcall/BackEndWork#22]
user masih dapat melihat service type dengan id vehicle yang dikombinasikan antara string, special character/numeric (ex: 2@a).
Expected result response code 404 Not found dan message "Not found"
Actual result response code 200 OK dan message "Success get specific service type"

![Image](https://user-images.githubusercontent.com/48172962/200341207-73a153c5-bf86-4a54-af57-4663a81c3b0a.png)

**Comment by RiovaldoTodoan** [comment]
Bug ini juga terjadi di admin
