### ISSUE TITLE
[BUG] in Update user profile (Cannot upload image)

### ISSUE THREAD

**Issue by Luqmanhanung** [ProjectBengcall/BackEndWork#26]
user tidak dapat mengupload image di PUT endpoint users pada images field.
Expected result response code 201 Created and message "Success Update user"
Actual result response code 520 dan response body berbentuk HTML
![Image](https://user-images.githubusercontent.com/48172962/200781378-082397ab-552e-42f1-a261-6fccb14ef345.png)

**Comment by LukmanulKhakim** [comment]
Uploud image sudah bisa dicoba
